#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GasApp.Droid.Resource", IsApplication=true)]

namespace GasApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon_old = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IconMinus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IconPlus = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int Minus = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Plus = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int botj8 = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int btnSolicitar = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int lbnBot13kg = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int lbnBot5kg = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int lbnBot8kg = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int lbnQuantidade = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int lbnprice13kg = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int lbnprice5kg = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int lbnprice8kg = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int nr13kg = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int nr5kg = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int nr8kg = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int relativeLayout1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int backgroundDefault = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int labelBot13kg = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int labelBot5kg = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int labelBot8kg = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int labelFooter = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int labelPedido = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int price13Kg = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int price5Kg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int price8Kg = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
